name: Build and Release Windows App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # Verwendet v5 (läuft nativ auf Node.js 24)
      - name: Checkout Code
        uses: actions/checkout@v5

      # Verwendet v5 mit Node.js 22 oder 24 für dein Projekt
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Windows Executable
        run: npm run make -- --platform=win32

      - name: Upload Executable to Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/make/squirrel.windows/x64/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}